### ISSUE TITLE
Get Cert Status

### ISSUE THREAD

**Issue by macflurry7** [gdbarron/VenafiTppPS#101]
Hello, have been using this amazing module since 1 month. Now I need to get the status of the cert and I'm not being able to. Can you help on this please @gdbarron ?

Thanks in advance

**Comment by gdbarron** [comment]
Hi @macflurry7.  Does `Get-TppCertificateDetail` provide what you are looking for?  If not, what specifically do you need?

**Comment by macflurry7** [comment]
Mmm, I'm not finding any field called status or something like that, you can find it when you click to see a cert in "general" first field.

**Comment by gdbarron** [comment]
When I select the General tab I see 2 sub-tabs, Log and Permissions.  Is this what you're referring to?  Perhaps a screenshot might help.

**Comment by macflurry7** [comment]
![image](https://user-images.githubusercontent.com/62151998/84006338-d861b480-a96e-11ea-9607-0b36440ae80f.png)

**Comment by gdbarron** [comment]
That will be in `ProcessingDetails.Status` when running `Get-TppCertificateDetail`.  You are not seeing a value because it is only populated when the cert is currently processing.  I'm not sure why it doesn't provide an 'OK' status.  @BeardedPrincess, any thoughts on this?

**Comment by gdbarron** [comment]
@macflurry7, does the prior comment provide you what you were looking for?

**Comment by macflurry7** [comment]
Hello @gdbarron Mmm no because I need to know actual status of any cert like "OK", "OK (Processing Disabled)" and things like that... That field is now empty using the API but it always has anything written... it would be perfect to get always the content of that field like the picture I provided before.

Thanks man

**Comment by gdbarron** [comment]
When the status shows 'OK' in the gui, meaning it's not current processing, `ProcessingDetails` will be blank.  If processing is disabled, the `Disabled` property from `Get-TppCertificateDetail` will be true.  Are there others status' you are looking for?

**Comment by macflurry7** [comment]
@gdbarron ok, it is ok. with some statements all working ok. You can close this too. Thank you for your support again!
