### ISSUE TITLE
Cannot download a cert with private key in "OpenSSL" format and with passphrase

### ISSUE THREAD

**Issue by macflurry7** [gdbarron/VenafiTppPS#102]
Hello, I was using this command at first

Get-TppCertificate -Path 'PATH' -Format 'OpenSSL' -OutPath 'PATH' -IncludePrivateKey -SecurePassword ($passphrase | ConvertTo-SecureString -asPlainText -Force)

but I got this error

Get-TppCertificate: Cannot validate argument on parameter 'Format'. The argument "Base64 (OpenSSL)" does not belong to the set "Base64,Base64 (PKCS #8),DER,JKS,PKCS #7,PKCS #12" specified by the ValidateSet attribute. Supply an argument that is in the set and then try the command again.

OK, just I use Base64 (this should be OpenSSL one by discard) and I'm getting this error
Format 'Base64' does not support private keys

I usually download like this (OpenSSL) with private key and passphrase through GUI and it works.

Can you help me on this please @gdbarron ? Thanks in advance

**Comment by macflurry7** [comment]
so here, should be one option in format called Base64 (OpenSSL) right?

**Comment by gdbarron** [comment]
My understanding is that OpenSSL is a tool, not a format.  I have just confirmed via Venafi's documentation that the list of formats in the module is correct (assuming their docs are correct).  If you are looking for Base64 with a private key, I think you should be using `Base64 (PKCS #8)`.

**Comment by macflurry7** [comment]
Thing is that via GUI I have one option called OpenSSL which I use usually + private key + passphrase. The thing is that I'm not being able to perform same action through CLI....

**Comment by macflurry7** [comment]
Alright thank you very much :)

**Comment by gdbarron** [comment]
Included in v2.0.
