### ISSUE TITLE
Passphrase for downloading a cert is always complaining about not conform to complexity requirements

### ISSUE THREAD

**Issue by macflurry7** [gdbarron/VenafiTppPS#105]
Hi @gdbarron. Why basic auth is not working now? I had changed my new-tppsession one liner and I'm getting this though

powershell/Modules/VenafiTppPS/2.0.0/Private/Invoke-TppRestMethod.ps1:136
"400 : {"Error":"Password does not conform to complexity requirements."}

It is not feasible that both methods can live together :D?

**Comment by gdbarron** [comment]
Hi @macflurry7.   Both key-based and token-based auth are both supported beginning with v2.0; see the examples.  You didn't provide the command line you are running, but if you run `New-TppSession` with `-verbose` and `-Credential` you will see the username and password; please confirm those are correct.  The key-based auth code is largely unchanged in this release.

**Comment by macflurry7** [comment]
Hi @gdbarron Sorry for my bad description before. It looks like that this is thrown by passphrase. I'm running this command for example.

Get-TppCertificate -Path $absolutepath -Format 'Base64' -OutPath 'PATH' -IncludePrivateKey -SecurePassword ($passphrase | ConvertTo-SecureString -asPlainText -Force)

**Comment by gdbarron** [comment]
That is strange.  When running with `-verbose`, does the payload look correct?  I'm wondering if this is a bug in the API.  Have you tried with a newer version?

Just FYI, general support ends for that version in a few weeks, July 1.

**Comment by macflurry7** [comment]
@gdbarron Mmm yes, we will be updating it these next weeks and we will try... hope it will work, you can close this and if it doesn't work, will open a new one.

Thank you for your support

**Comment by gdbarron** [comment]
Sounds good, thanks.

**Comment by macflurry7** [comment]
Hello @gdbarron Please reopen this. I'm in same state but now in Version 19.4.0.3361 and throwing me same error

.local/share/powershell/Modules/VenafiTppPS/2.0.0/Private/Invoke-TppRestMethod.ps1:136
Line |
 136 |  …             throw ('"{0} {1}: {2}' -f $_.Exception.Response.StatusCod …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | "400 : {"Error":"Password does not conform to complexity requirements."}

BTW, Im using this passphrase: rufFji$4MOYiEaACv@o72VyY

No way man :(
