### ISSUE TITLE
Cannot use Invoke-TppRestMethod

### ISSUE THREAD

**Issue by wilddev65** [gdbarron/VenafiTppPS#106]
When using the various functions available in VenafiTppPS there can sometimes be a particular API call that is not available which would need a custom function setup. While TppSession info is available to use when adding this to a script, the 'Invoke-TppRestMethod' function is private and not available to use. It would be helpful to be able to use this to make the call to the Venafi API.

**Comment by gdbarron** [comment]
Hey @wilddev65.  I've made this function public, https://www.powershellgallery.com/packages/VenafiTppPS/2.0.1.  If there are specific api calls you think folks would find useful, please feel free to submit an issue or PR.
