### ISSUE TITLE
Cannot download Cert "Password does not conform to complexity requirements"

### ISSUE THREAD

**Issue by macflurry7** [gdbarron/VenafiTppPS#108]
Hello @gdbarron  I'm in same state but now in Version 19.4.0.3361 and throwing me same error

.local/share/powershell/Modules/VenafiTppPS/2.0.1/Private/Invoke-TppRestMethod.ps1:146
Line |
146 | … throw ('"{0} {1}: {2}' -f $_.Exception.Response.StatusCod …
| ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| "400 : {"Error":"Password does not conform to complexity requirements."}

BTW, Im using this passphrase: rufFji$4MOYiEaACv@o72VyY

No way man :(

**Comment by gdbarron** [comment]
Hey @macflurry7.  I'll need to fire up Linux and test this.  I still have the command you were running from the prior issue, but can you please provide the verbose output of your run?  Try and include as much of the detail as possible without compromising security.  You've already provided the password you are using so please include that part of the output as well.

**Comment by macflurry7** [comment]
Verbose now

WARNING: Key-based authentication will be deprecated in release 20.4 in favor of token-based
VERBOSE: Expires: 6/19/2020 12:48:29 PM, Current (+2s): 6/19/2020 12:45:51 PM
VERBOSE: {
  "Headers": {
    "X-Venafi-Api-Key": "XXXXXXXXXXXXX"
  },
  "Method": "Post",
  "ContentType": "application/json",
  "Body": "{\n  \"CertificateDN\": \"\\\\Ved\\\\Policy\\\\Certificates\\\\test\\\\test.test.test\",\n  \"IncludePrivateKey\": true,\n  \"Password\": \"s\",\n  \"Format\": \"Base64\"\n}",
  "Uri": "https://machine.domain.com/vedsdk/certificates/retrieve"
}
VERBOSE: POST https://machine.domain.com/vedsdk/certificates/retrieve with 146-byte payload
VERBOSE: received 65-byte response of content type application/json
Exception: $HOME/.local/share/powershell/Modules/VenafiTppPS/2.0.0/Private/Invoke-TppRestMethod.ps1:136
Line |
 136 |  …             throw ('"{0} {1}: {2}' -f $_.Exception.Response.StatusCod …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | "400 : {"Error":"Password does not conform to complexity requirements."}

I will try in Windows too to see if it is running there

**Comment by gdbarron** [comment]
Looks like the password is coming through as "s" which is quite odd considering the password you are using, rufFji$4MOYiEaACv@o72VyY, doesn't even have an "s" in it.  Can you provide me the full code you are running?

**Comment by macflurry7** [comment]
So, that should be the bug @gdbarron !
Get-TppCertificate -Path $absolutepath -Format 'Base64' -OutPath '$localpath' -IncludePrivateKey -SecurePassword ($passphrase | ConvertTo-SecureString -asPlainText -Force) -verbose

**Comment by gdbarron** [comment]
Please include the full code including setting of vars used in Get-TppCertificate. Looking for a complete picture to replicate.

I also noticed that the value for outpath has single quotes around it. Are you running it that way?  It won't cause this issue, but will be a problem once fixed.

**Comment by macflurry7** [comment]
@gdbarron paths are OK, they were replaced by me for putting the command here!!

Get-TppCertificate -Path '\ved\policy\oldcert\cert' Format 'Base64' -OutPath '/path' -IncludePrivateKey -SecurePassword ($passphrase | ConvertTo-SecureString -asPlainText -Force) -verbose

Same like this

**Comment by gdbarron** [comment]
Please either provide me the full code including where you set the variable `passphrase` or replace the passphrase variable with the actual value and run it and provide me the code and verbose output. I need to see the whole picture. Can't continue without it.

**Comment by macflurry7** [comment]
Ok, full code will be for example

Declaring passphrase variable
$passphrase="Passphrase.8"

Get-TppCertificate -Path '\ved\policy\oldcert\cert' Format 'Base64' -OutPath '/path' -IncludePrivateKey -SecurePassword ($passphrase | ConvertTo-SecureString -asPlainText -Force) -verbose

This is not working

**Comment by gdbarron** [comment]
@macflurry7, unfortunately, I'm going to need to close this issue if you aren't able to provide the needed info.  I need to see an end to end, all the code and verbose output in one run.  If you are able to provide this I am happy to troubleshoot, otherwise, no worries, we can close this.  Please let me know.

**Comment by BeardedPrincess** [comment]
@macflurry7 I think we should try another approach. Would you please open a ticket with Venafi support, and reference this issue by URL. If you can let me know the ticket number in here, I can add myself to the the ticket and see if we can work it out from this side.

I’d like to get to the bottom of this for you, and if there’s an issue with either the API or this module we will be able to resolve it for others too.

Thanks!

**Comment by gdbarron** [comment]
@BeardedPrincess, I think we'd all like to get to the bottom of this.  Just need a walkthru of the code and verbose output in one shot.  There is an invalid password in one verbose output, but we don't have the code to match it up.  At this point, that's what needed.  Kindly keep the conversation here so it can be properly tracked and referenced by all.

**Comment by macflurry7** [comment]
Hello @gdbarron @BeardedPrincess sorry for the delay, I was on vacation. I will share the code and the verbose output. No problem but I shared it before 👍 

Code:

$passphrase="l1Xgf2yih4Dm3NIDF7hu."

$Credentials = Get-Credential

New-TppSession -Server https://SERVER -Credential $Credentials


Get-TppCertificate -Path '\ved\policy\Certificates\test\test.test' -Format 'Base64' -OutPath '/compartida/' -IncludePrivateKey -SecurePassword ($passphrase | ConvertTo-SecureString -asPlainText -Force) -verbose
#######################################################################################

Verbose output

WARNING: Key-based authentication will be deprecated in release 20.4 in favor of token-based
VERBOSE: Expires: 6/29/2020 11:29:50 AM, Current (+2s): 6/29/2020 11:27:04 AM
VERBOSE: {
  "Method": "Post",
  "Uri": "https://SERVER/vedsdk/certificates/retrieve",
  "ContentType": "application/json",
  "Body": "{\n  \"Format\": \"Base64\",\n  \"Password\": \"l\",\n  \"IncludePrivateKey\": true,\n  \"CertificateDN\": \"\\\\ved\\\\policy\\\\Certificates\\\\test\\\\test.test\"\n}",
  "Headers": {
    "X-Venafi-Api-Key": "xxxXXXxxx"
  }
}

VERBOSE: POST https://SERVER/vedsdk/certificates/retrieve with 146-byte payload
VERBOSE: received 65-byte response of content type application/json
Exception: ~/.local/share/powershell/Modules/VenafiTppPS/2.0.1/Public/Invoke-TppRestMethod.ps1:146
Line |
 146 |  …             throw ('"{0} {1}: {2}' -f $_.Exception.Response.StatusCod …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | "400 : {"Error":"Password does not conform to complexity requirements."}

**Comment by gdbarron** [comment]
Fixed in [v2.0.2](https://www.powershellgallery.com/packages/VenafiTppPS/2.0.2).  This was specific to PowerShell Core on Linux.  Let me know if by some chance this doesn't resolve your issue.
