### ISSUE TITLE
Setup instructions

### ISSUE THREAD

**Issue by Saadi6** [gdbarron/VenafiTppPS#111]
Hi @gdbarron. To make it dead-simple for new users who are not that familiar with PowerShell, can you please add couple of lines to ReadeMe or docs on how to start using this module? It can be as simple as this:

1. Download zip then unzip to a folder.
2. Open PS then change directory to VenafiTppPS\Code.
3. Type in **Import-Module .\VenafiTppPS.psd1** to load VenafiTppPS.
4. Authenticate as $cred = Get-Credential; New-TppSession -ServerUrl 'https://venafi.mycompany.com' -Credential $cred
5. Enjoy all the new cool commands available in your PS session to interact with Venafi!

Thanks!

**Comment by gdbarron** [comment]
Hey @Saadi6.  I've updated the readme to include some getting started details.  Hopefully that's what you were looking for.  I do not recommend folks pull from github directly as the published module on psgallery might be different due to the build/release process.

**Comment by Saadi6** [comment]
Thanks, those instructions are easy to understand and should make it easier for anyone to get started!
