### ISSUE TITLE
Change Validity Period is not working

### ISSUE THREAD

**Issue by macflurry7** [gdbarron/VenafiTppPS#113]
Set-TppAttribute -Path $absolutepath -AttributeName 'Validity Period' -Value '3'

Putting different values... but it is always setting this value to 1, so it is not working. Can you help on this?

Regards

**Comment by gdbarron** [comment]
Hi @macflurry7.  What version are you using?  Can you please run with `-verbose` and provide the output and response from the function?

When you created the issue, did you see an option for templates, eg. Bug Report?  I'd like folks to start using that so needed info is captured up front, but want to make sure folks see it.  Thanks.

**Comment by macflurry7** [comment]
Hello @gdbarron. Sorry for not using template, I will be using it next time!

VenafiTPP version => 19.4.2.3872
venafitppps version => 2.0.2

Command run:

Set-TppAttribute -Path '\Ved\Policy\PATH' -AttributeName 'Validity Period' -Value '2' -verbose

VERBOSE: Expires: 8/6/2020 3:45:31 PM, Current (+2s): 8/6/2020 3:46:06 PM
VERBOSE: GET https://SERVER/vedsdk/authorize/checkvalid with 0-byte payload
VERBOSE: received 88-byte response of content type application/json
VERBOSE: Content encoding: utf-8
VERBOSE: Performing the operation "Overwrite attribute values" on target "\VED\Policy\PATH".
VERBOSE: {
  "ContentType": "application/json",
  "Uri": "https://SERVER/vedsdk/config/Write",
  "Body": "{\n  \"Values\": [\n    \"2\"\n  ],\n  \"AttributeName\": \"Validity Period\",\n  \"ObjectDN\": \"\\\\VED\\\\Policy\\\\PATH\"\n}",
  "Headers": {
    "X-Venafi-Api-Key": "XXXxxxXXX"
  },
  "Method": "Post"
}

VERBOSE: POST https://SERVER/vedsdk/config/Write with 213-byte payload
VERBOSE: received 12-byte response of content type application/json
VERBOSE: Content encoding: utf-8

but it is always setting this value to '1' Please see:

![image](https://user-images.githubusercontent.com/62151998/89553177-7bb73480-d80d-11ea-98d7-0401df787255.png)

**Comment by macflurry7** [comment]
Oh, I see another thing here, With ps module it shows me different number that venafitpp GUI. For example

Get-TppAttribute -path '\VED\Policy\PATH' |Where {$_.name -eq "Validity Period"}

Name            Value IsCustomField CustomName
----            ----- ------------- ----------
Validity Period 3             False

![image](https://user-images.githubusercontent.com/62151998/89554033-98a03780-d80e-11ea-9b78-36e830862861.png)

**Comment by macflurry7** [comment]
Hello @gdbarron This is already working but it is working with days through the API 👍 so setting for example this value to 1095 already set the validity perior to 3 years. So nothing to fix here.
