### ISSUE TITLE
get-tppcertificatedetail not providing field "Description" from TPP

### ISSUE THREAD

**Issue by doyle043** [gdbarron/VenafiTppPS#119]
# Environment

```
Operating System: windows 10
VenafiTppPS version: 2.0.5
PowerShell version: 5.1.18362.1110
```

# Steps to reproduce

get-tppcertificatedetail -GUID 'anyguidID'

# Expected behavior

Expected get-tppcertificationdetail to provide field Description as per documentation

# Actual behavior

get-tppcertificationdetail is not returning description field anywhere (not even in the multivalue fields)

# Screenshots

Provided text as institutional filters prevent image

PS C:\Users\bdoyle1> get-tppcertificatedetail -GUID 'e578ea89-adfc-445b-9cac-e297e1fb87b0'

Name                   : testcert.vfidev.com
TypeName               : X509 Server Certificate
Path                   : \VED\Policy\Certificates\API\Requestor_Generated_CSR\testcert.vfidev.com
Guid                   : e578ea89-adfc-445b-9cac-e297e1fb87b0
ParentPath             : \VED\Policy\Certificates\API\Requestor_Generated_CSR
Approver               : {local:{53455e2e-9cb9-45f8-8c71-4d171a519b99}}
CertificateAuthorityDN : \VED\Policy\Administration\CAs\E3-Webserver-AFISubCA1
CertificateDetails     : @{AIACAIssuerURL=System.Object[]; AIAKeyIdentifier=0C0EDEE39CE26573014B6107D1EB948AF8EFA297;
                         C=US; CDPURI=0::False:ldap:///CN=AFISubCA1(1),CN=MSPCSC12CCCA01,CN=CDP,CN=Public%20Key%20Servi
                         ces,CN=Services,CN=Configuration,DC=i,DC=ameriprise,DC=com?certificateRevocationList?base?obje
                         ctClass=cRLDistributionPoint; CN=testcert.vfidev.com; EnhancedKeyUsage=Client
                         Authentication(1.3.6.1.5.5.7.3.2),Server Authentication(1.3.6.1.5.5.7.3.1);
                         Issuer=CN=AFISubCA1, DC=i, DC=ameriprise, DC=com; KeyAlgorithm=RSA; KeySize=2048;
                         KeyUsage=KeyEncipherment, DigitalSignature; L=Minneapolis; O=Venafi; OU=System.Object[];
                         PublicKeyHash=C9D771D0E8660301066278CF3D4670DA9151BD3A; S=Minnesota;
                         SKIKeyIdentifier=366EB12D690EF927E9EB86EDDC0E4A1486F8A6F1;
                         Serial=2E00062D406F70FD4DC848CD6D000100062D40; SignatureAlgorithm=sha256RSA;
                         SignatureAlgorithmOID=1.2.840.113549.1.1.11; StoreAdded=2020-10-14T22:50:48.4748531Z;
                         Subject=CN=testcert.vfidev.com, OU=BizDev, O=Venafi, L=Minneapolis, S=Minnesota, C=US;
                         SubjectAltNameDNS=System.Object[]; TemplateMajorVersion=100; TemplateMinorVersion=36;
                         TemplateName=AFI-WebServer-AutoCreation; TemplateOID=1.3.6.1.4.1.311.21.8.6963390.1297995.1476
                         3659.10736412.8893591.125.13860656.4053856;
                         Thumbprint=FD7D6FB976CCF3C70438BCBD5ADFF10EB1C94E8C; ValidFrom=2020-10-14T22:40:48.0000000Z;
                         ValidTo=2022-10-14T22:40:48.0000000Z}
Contact                : {local:{53455e2e-9cb9-45f8-8c71-4d171a519b99}}
CreatedBy              : {Web SDK}
CreatedOn              : 2020-10-14T22:50:46.0998415Z
ManagementType         : Enrollment
ProcessingDetails      :
RenewalDetails         : @{City=Minneapolis; Country=US; KeySize=2048; Organization=Venafi;
                         OrganizationalUnit=System.Object[]; State=Minnesota; Subject=testcert.vfidev.com}
ValidationDetails      : @{LastValidationStateUpdate=2020-10-15T00:00:07.0000000Z; ValidationState=Failure}

**Comment by gdbarron** [comment]
Hi @doyle043, thanks for the info.  In looking at what the api provides, description is not one of the properties.  I see the links in the help refer to v18.1 of which the docs are no longer available, but I'm assuming that used to be there and isn't now or...I just messed up.  I'll get the help updated to accurately reflect the output.
