### ISSUE TITLE
Verbose param leaks passwords from basic auth

### ISSUE THREAD

**Issue by bwright86** [gdbarron/VenafiTppPS#120]
I'm new to using the module, and noticed that `-Verbose` will return details from the Invoke-RestMethod call, which includes the username/password in the Body block.

This behavior could lead to leaked passwords for users, either from peers sitting beside you, or from Powershell transcripts capturing output in text files (This is the case for me, as i have to go back and scrub the file).

It would be easy to add a `-Verbose:$false` in the below text to prevent leaking password details:
https://github.com/gdbarron/VenafiTppPS/blob/99bc2c00f2686fac511affa50609eab5cb1ec823/VenafiTppPS/Code/Classes/TppSession.ps1#L88

There may be other locations that could leak this detail as well, I will post them as I find them.

It looks like there is a push to move to Token Based authentication in the future, which is a good move. But Tokens are still sensitive, so it would probably be helpful to prevent leaking those as well.

I would be curious if there is a use case where returning the verbose detail from this call would be necessary, if there is a case, some mechanism that is difficult to trigger could be implemented to allow it to be returned.

**Comment by bwright86** [comment]
It looks like this cmdlet would do the same:
https://github.com/gdbarron/VenafiTppPS/blob/99bc2c00f2686fac511affa50609eab5cb1ec823/VenafiTppPS/Code/Public/New-TppToken.ps1#L144

(Not sure if this is the case only for OAuth or if Integrated `UseDefaultCredentials` would do the same.)

**Comment by bwright86** [comment]
Looks like these cmdlets as well:
https://github.com/gdbarron/VenafiTppPS/blob/7c7c3dfaf46b0543d6576cf978b06c9514761d51/VenafiTppPS/Code/Public/Get-TppCertificate.ps1#L164
https://github.com/gdbarron/VenafiTppPS/blob/6db33c9f19fa8d54bc03de84c290099badf5e855/VenafiTppPS/Code/Public/Import-TppCertificate.ps1#L152

**Comment by gdbarron** [comment]
Hey @bwright86, thanks for submitting this.  I've been meaning to do this for a while and just never got around to it 😄

I'd like to keep the verbose output for all the other rest params which I've found to be very helpful.  I will look to just hide the private/secret info.  Providing the location where the info should be hidden is a big help, thanks.  I'll get working on this.

**Comment by bwright86** [comment]
Hey @gdbarron, sounds good. If you would like a PR for this, I can create one.

I ended up putting a patch into the Invoke-TppRestMethod to handle this. If it found hash keys in the Body for ‘password’ or ‘token’, it would create a ‘redactedparams’ hashtable, replace the value with “[Redacted]”, and provide the correct hashtable to ‘Write-Verbose’ and the Invoke call.

This worked well, and even caught the scenario where ‘Get-TppCertificate’ passed a password for encrypting the private key.

Thanks for the response!

**Comment by gdbarron** [comment]
Nice work on the patch!  I took a similar approach, but with some differences.  I wanted to be able to capture the params on the way in and verbose on the way out so I created a function to handle both.  Let me know what you think.  https://github.com/gdbarron/VenafiTppPS/compare/hide-verbose-logging-secrets

The code isn't finished yet, but should be mostly functional.

**Comment by bwright86** [comment]
Cool, I like the idea of splitting the function out to its own cmdlet.

I will pull this down tomorrow and give it a whirl.

Thanks for looking into it!

**Comment by gdbarron** [comment]
Hey @bwright86.  Get a chance to give it a shot?  Thanks.

**Comment by gdbarron** [comment]
> Looks like these cmdlets as well:
> https://github.com/gdbarron/VenafiTppPS/blob/7c7c3dfaf46b0543d6576cf978b06c9514761d51/VenafiTppPS/Code/Public/Get-TppCertificate.ps1#L164
> 
> 
> https://github.com/gdbarron/VenafiTppPS/blob/6db33c9f19fa8d54bc03de84c290099badf5e855/VenafiTppPS/Code/Public/Import-TppCertificate.ps1#L152

These don't write-verbose directly, but leave it to `Invoke-TppRestMethod` to write it out so updating that one function covers these.

**Comment by gdbarron** [comment]
I had missed hiding the Authorization value in the header, but have now added that as well, https://github.com/gdbarron/VenafiTppPS/commit/16ddae4172a7e0ea58c2c87fe93542e9a3e975d4

**Comment by bwright86** [comment]
Cool, good catch, I was curious if there were other sensitive values. I haven’t had a chance to try the improvements, I had been running with my patched version, and it worked well. I will be back in the office on Tuesday, so I can give the updates a once over.

**Comment by bwright86** [comment]
I pulled down the changes you made, and moved it into a patched version "2.0.5.2" on my side to test. It seems i am still leaking passwords w/ the Verbose parameter.

I'm guessing the issue on my side is around the Regex expressions being used, but i don't have the time currently to dive into the expressions. I am currently using PSv5.1 on my side.

Would it be difficult to walk through the hashtable to look for sensitive data, versus searching through JSON strings w/ RegEx?

**Comment by gdbarron** [comment]
It's a hashtable going in, but json coming out so went with the approach I did.  I'm open to other ideas.  If you can let me know what commands you are running I can see if I can replicate.  I'm using v7.1, but will test with v5.1 as well.

**Comment by gdbarron** [comment]
Found the issue.  The formatting between v5 and v7 is slightly different where there's an extra space with v5.

``` powershell
# PS v5 has 2 spaces between key:  value
# PS v7 has 1 space between key: value
```

I've updated the branch.

**Comment by bwright86** [comment]
Cool, I don’t think I was sure of the approach you took, but it is clearer now.

I am not sure if the regex engine has changed between PSv5.1 and PSv7.x. I am aware it is a .NET flavor, and since PSv7 uses .NET Core, there could be some differences.

I think we can keep with your flow of converting to JSON and then doing a regex replacement.

**Comment by bwright86** [comment]
Wow, that is a great find. So it was an issue in the JSON converter. Wonderful!
