### ISSUE TITLE
Unable to search for TppObjects when using OAuth Tokens

### ISSUE THREAD

**Issue by smokey7722** [gdbarron/VenafiTppPS#122]
We are updating a script implemented last year using VenafiTppPS to utilize tokens and are running into an issue.  Using Integrated authentication it works perfectly but when attempting to create a session using a token, I am unable to query objects.  The full script logs into Microsoft Azure and pulls all of the Enterprise Applications for SSO, then copies their certificates into Venafi for reporting purposes only.  The script works great using Integrated authentication and will pull the data from Azure, then create certificates in Venafi or updates/deletes existing ones.  

I am hoping this is just a simple issue that I am running into but figured before we escalate to Venafi it would be worth checking here first in case it is something blatantly simple that I am just missing?  We have verified my user has full permissions for Certificates so I think I have the appropriate roles correct in the Scope for the Token session but am thinking maybe that could be what the issue is?

# Environment

```
Operating System:
VenafiTppPS version: 2.0.5
Venafi version 20.1
PowerShell version: 5.1
```

# Steps to reproduce
Token request
1) Request a new OAuth token
```
$cred = (Get-Credential)
$token = New-TppSession -Server dcm-qa -ClientId AppGallery -Scope @{'certificate'='manage,delete'} -Credential $cred -Passthru -Verbose
```
2) Query an existing policy resulting in a listing of all objects within the policy
```
Find-TppObject -TppSession $token -Path "\ved\policy\Test\" -Recursive
```

Integrated Request
1) Request a new OAuth token
```
$cred = (Get-Credential)
$integrated = New-TppSession -Server dcm-qa -Credential $cred -Passthru -Verbose
```
2) Query an existing policy resulting in a listing of all objects within the policy
```
Find-TppObject -TppSession $integrated -Path "\ved\policy\Test\" -Recursive
```

# Expected behavior
I would expect Find-TppObject to respond with the objects within the path when using OAuth or Integrated authentication. 

# Actual behavior
When executing the Token request version, I get an error of 404 Not Found / Service Endpoint not found as shown in the image below.  

When executing the legacy Integrated request version, it works perfectly.

# Screenshots
![image](https://user-images.githubusercontent.com/5751732/102283064-859d2280-3ee6-11eb-9015-31d326399214.png)

**Comment by gdbarron** [comment]
Hi @smokey7722.  I'm wondering if your issue has anything to do with how you're calling `New-TppSession`.  When running `New-TppSession`, it will only return a session object if you use `-PassThru`.  It could be you have cached credentials and that's part of the reason why you are seeing some odd behavior.  To be fair, I wouldn't expect to see a 404 due to this though.  Can you start a new PS session, execute `$TppSession` to ensure it has no value, add `-PassThru` to the `New-TppSession` call and try again?  If this doesn't work, please provide verbose output for each call in the screenshot.

**Comment by smokey7722** [comment]
Sorry looks like I copy/pasted skipping the -Passthru.  I updated the original post to include it on both connections as it has been included in all.  I've created new PS sessions, changed variables names, etc and see the same behavior.  The screenshot included is the verbose output from a Find-TppObject execution using a token.

I can't get into the system now, as there is maintenance going on, to re-run commands but am hoping to be able to get in tonight or tomorrow.

**Comment by gdbarron** [comment]
The screenshot only has the resulting error, not the verbose output.  If you could please provide it as well that would be great.

**Comment by smokey7722** [comment]
Please see the screenshots below - Sorry about the delay, connectivity issues into the lab environment slowed me down.

Session creation using token:
![session_token](https://user-images.githubusercontent.com/5751732/102819674-c5ea1e00-4388-11eb-8c02-02ddb0af50d3.png)

Find using token session:
![find_token](https://user-images.githubusercontent.com/5751732/102819696-cf738600-4388-11eb-889b-e50b418fe333.png)

Session creation using integrated:
![session_integrated](https://user-images.githubusercontent.com/5751732/102819710-d9958480-4388-11eb-99b3-4ec01c6b1315.PNG)


Find using integrated session:
![find_integrated](https://user-images.githubusercontent.com/5751732/102819703-d7cbc100-4388-11eb-8ee5-ae0d72923d6f.PNG)

**Comment by gdbarron** [comment]
Perfect, thanks.  That 404 is bogus and I already have the fix to reveal the real error in the latest branch.

Your current issue is due to the scope you are using, `@{'certificate'='manage'}`.  A call to Find-TppObject uses the [config/enumerate api](https://docs.venafi.com/Docs/20.4SDK/TopNav/Content/SDK/WebSDK/r-SDK-POST-Config-enumerate.php?tocpath=Web%20SDK%7CConfig%20programming%20interface%7C_____13) which requires a scope of configuration with any privilege; `@{'configuration'=$null}` or `@{'configuration'='manage'}` should get it done.  Please let me know if this is indeed the issue.

Once the new version is released, you will see a different error in this case which tells you the required scope.

**Comment by smokey7722** [comment]
Awesome, I had a feeling this was based on how I was issuing the commands for specific permissions/scopes.  I will test this today to see if those scopes help instead.  As we'll need to be able to create/update/delete certificates I assume we still need certificate=manage permissions but will also need configuration null or manage granted as well as part of the token so I will try that.

I look forward to the next version as well for the obfuscation of sensitive data like passwords was going to be something I was going to post asking about at some point.

**Comment by gdbarron** [comment]
Delete is a different privilege so you'll need to use `@{'certificate'='manage,delete'}`.  You can find the scope to privilege mapping at https://docs.venafi.com/Docs/20.4SDK/TopNav/Content/SDK/AuthSDK/r-SDKa-OAuthScopePrivilegeMapping.php?tocpath=Auth%20SDK%20reference%20for%20token%20management%7C_____5.

**Comment by smokey7722** [comment]
> Delete is a different privilege so you'll need to use `@{'certificate'='manage,delete'}`. You can find the scope to privilege mapping at https://docs.venafi.com/Docs/20.4SDK/TopNav/Content/SDK/AuthSDK/r-SDKa-OAuthScopePrivilegeMapping.php?tocpath=Auth%20SDK%20reference%20for%20token%20management%7C_____5.

Yup I had that down to add delete in the session request.  For now just doing one single task at a time.

**Comment by smokey7722** [comment]
Adding configuration=manage looks like it worked and lets me do a search.  I'm working through some other testing but hope to test my script end to end within the next day or so to verify the full Azure -> Venafi functionality still works after the switch to using tokens.

**Comment by gdbarron** [comment]
Cool, glad it worked. If you have any questions, feel free to open another issue or you can use the new Discussion feature.
