### ISSUE TITLE
Revoke-TppToken cannot be forced

### ISSUE THREAD

**Issue by stevekeever** [gdbarron/VenafiTppPS#129]
# Environment

```
Operating System: Windows
VenafiTppPS version: 2.2.0
PowerShell version: 5.1
```

# Steps to reproduce

Revoke-TppToken -TppSession $mySession

# Expected behavior

I would expect the token to be revoked. 

# Actual behavior

However this is displayed:
Performing the operation "Revoke token" on target "".
[Y] Yes [A] Yes to All [N] No [L] No to All [S] Suspend [?] Help (default is "Yes"): y

I would expect this behavior only if the -Confirm was sent.

**Comment by gdbarron** [comment]
Hey @stevekeever.  This is typical of destructive functions as ConfirmImpact is set to High.  You can either change `$ConfirmPreference` or pass in `-Confirm:$false` to the function.  For better or worse, this is expected behavior.

**Comment by gdbarron** [comment]
@stevekeever, ok to close this?

**Comment by stevekeever** [comment]
Thanks!  Confirmed.
