### ISSUE TITLE
New-tppsession confusion

### ISSUE THREAD

**Issue by fearnie85** [gdbarron/VenafiTppPS#136]
Hi Team,

I am a little confused on connecting to the venafi portal following the documentation -  https://venafitppps.readthedocs.io/en/latest/functions/New-TppSession/

I am attempting to login using my credentials, but I get 

`New-TppSession : Cannot validate argument on parameter 'Server'. Please enter a valid server, https://venafi.company.com or venafi.company.com`

I believe the reason for this is because our server has /vedadmin in the URL.

Is there something I am doing wrong? or is there some way around this?

If I try without the forward slash content, I get the following error.
`"404 Not Found: 
Network Error`

Any help is appreciated.

Thanks.

**Comment by gdbarron** [comment]
Can you please provide a sample of the command you are running?  Are you trying to use key or token based auth?  `-Server` should be just as the error states, eg. `New-TppSession -Server venafi.domain.com`.

/vedadmin is what is used to access the site via a browser, not via the api.  /vedsdk is used for all of the api calls except for token-based auth which used /vedauth.

**Comment by fearnie85** [comment]
Sure, I am trying to login using credentials. 

New-TppSession -Server "clm.internaldomain.company.externaldomain" -Credential $vencred

Accessing our web portal works with - clm.internaldomain.company.externaldomain and then the /vedadmin

Am I doing something wrong? Thanks

**Comment by gdbarron** [comment]
Hmmm, I'm wondering if the validation is only expecting a third level domain and not a fourth. I can try that on my end.

**Comment by gdbarron** [comment]
Nope, that's not it.  I got `The remote name could not be resolved`, not param validation errors.  What version of the module, ps, and OS are you using?  Can you provide the entire command with `-verbose` and the output just in case I see something?

**Comment by fearnie85** [comment]
its ok, I fixed it :) it was my fault :) I got the link wrong

**Comment by fearnie85** [comment]
my fault, I got the API link wrong. seems we have 2 environments.
