### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by fearnie85** [gdbarron/VenafiTppPS#149]
Found an error when trying to get expired certificates.

I have noticed that some certificates within this folder are not actually expired, hence using the  -ExpireBefore (Get-Date).

Thanks.

`Find-TppCertificate -Path '\VED\Policy\_Discovered\Agents\Expired\' -ExpireBefore (Get-Date) -Recursive
"500 Internal Server Error: {"ErrorDetails":"Failed to load certificate list due to a query error, please check the query parameters and try again. Error details: Failed to execute 
query\u000d\u000aExecution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.\u000d\u000aThe statement has been terminated.\u000d\u000aThe 
wait operation timed out\u000d\u000a"}
At C:\Program Files\WindowsPowerShell\Modules\VenafiTppPS\2.2.2\Public\Invoke-TppRestMethod.ps1:154 char:17
+ ...             throw ('"{0} {1}: {2}' -f $originalError.Exception.Respon ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: ("500 Internal S...u000d\u000a"}
:String) [], RuntimeException
    + FullyQualifiedErrorId : "500 Internal Server Error: {"ErrorDetails":"Failed to load certificate list due to a query error, please check the query parameters and try again. Error details: Failed to e 
   xecute query\u000d\u000aExecution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.\u000d\u000aThe statement has been terminated.\u000d  
  \u000aThe wait operation timed out\u000d\u000a"}`

**Comment by gdbarron** [comment]
The error says there was a timeout.  Not sure I'm following what the issue with the code is.  Is the server in a good state?

**Comment by fearnie85** [comment]
Oh sorry. I have found the issue. I forgot I added it there.

It's a local issue. It's regarding server timeout.
