### ISSUE TITLE
lists

### ISSUE THREAD

**Issue by Curtmcgirt** [gdbarron/VenafiTppPS#153]
how would i produce a list of all apps associated with a certain certificate? 

how would i produce a list of all capi apps with a friendly name attribute of "this.that.com"

**Comment by gdbarron** [comment]
Hi @Curtmcgirt.  This project is now deprecated and has been replaced with VenafiPS.  Can you please resubmit this at https://github.com/gdbarron/VenafiPS?  Also, there is a discussion section which is perfect for this.  Thanks!
