### ISSUE TITLE
Implement Get-TppVersion

### ISSUE THREAD

**Issue by gdbarron** [gdbarron/VenafiTppPS#2]
Implement Get-TppVersion.  This helps the user know which functions are available.  Add this to the session object so we can easily track.

**Comment by gdbarron** [comment]
@BeardedPrincess, did you have interest in working on this one?

**Comment by BeardedPrincess** [comment]
Yes.. sorry, been out of the country for a bit.  

This is actually pretty simple. If you do a 'config/read' against ObjectDN '\VED' for AttributeName 'Schema Version' you'll find the version info there. You're interested in the 'CORE' value.

**Comment by BeardedPrincess** [comment]
Closing the loop on this.. about the time of this issue, I raised an ER with the product team to add a supported way to get the version of TPP via the API that didn't require any additional permissions. The result of that was the addition of the GET /SystemStatus/Version call in TPP 18.3. It should work for any valid API user.
