### ISSUE TITLE
Add License Information

### ISSUE THREAD

**Issue by BeardedPrincess** [gdbarron/VenafiTppPS#28]
@gdbarron ,

This project is shaping up nicely. I'm contemplating using it in some of my projects, but am curious on what license you're planning to release this under? Have I missed that documented somewhere?

I think this will be of particular interest to enterprise users as well.

**Comment by gdbarron** [comment]
I meant to take care of this when I first started the project, but that didn't happen.  Here you go, https://github.com/gdbarron/VenafiTppPS/blob/master/LICENSE
