### ISSUE TITLE
Module can't find function Invoke-TPPRestMethod

### ISSUE THREAD

**Issue by BeardedPrincess** [gdbarron/VenafiTppPS#33]
@gdbarron when doing a clean install using 'Install-PSModule VenafiTPPPs', the Invoke-TPPRestMethod is imported in such a way that I can't establish a session.

Steps to repro:

![image](https://user-images.githubusercontent.com/28336998/40194810-e111daa8-59c8-11e8-81fb-706c368afb1e.png)

**Comment by gdbarron** [comment]
@BeardedPrincess, this should be fixed. The build process messed with my manifest.

**Comment by BeardedPrincess** [comment]
0.3.2 looks good!
