### ISSUE TITLE
Venafi TPP icon usage

### ISSUE THREAD

**Issue by gdbarron** [gdbarron/VenafiTppPS#37]
Hey @BeardedPrincess.  Would you guys be open to using a Venafi/TPP icon with this module?  Didn't want to use it without permission.  Thanks.

**Comment by BeardedPrincess** [comment]
Wow.. just realized I never responded to this, from over a year ago! Sorry about that! (The email account associated with this account gets a ton of emails to the point I hardly look closely at it!).

I'll send a note to marketing to see what I can find out.

**Comment by BeardedPrincess** [comment]
Email sent, but still haven't heard anything back on this... I'll keep you posted.

**Comment by gdbarron** [comment]
Hey @BeardedPrincess, just checking in, any update?  Thanks!

**Comment by wilddev65** [comment]
I'm going to try to ask some questions internally to see if I can get permission for this
