### ISSUE TITLE
Get identity info and provide intelligent filtering

### ISSUE THREAD

**Issue by gdbarron** [gdbarron/VenafiTppPS#46]
[Getting identity info](https://github.com/gdbarron/VenafiTppPS/blob/aug13-identity-stuff/VenafiTppPS/Code/Public/Get-TppIdentity.ps1) has been added via browse and self.  @Saadi6, can you help me understand why you suggested another function to filter these results as opposed to providing a more unique value, eg. email address, up front?  Thanks.

**Comment by Saadi6** [comment]
Hi. The function Get-Identity looks fine to me. It returns an object with one or more identities, which is correct for its' purpose. The caller should decide what to do with the identities in the returned object. So if the caller was expecting a single identity for 'Clark Kent' then it should count matched identities and handle accordingly.

There is no issue here, this can be closed.

A companion function to read any specified attribute for a given universal id, such as an email address or another attribute from the directory would be useful. This can be a simple function that uses Identity/ReadAttribute to return the value from directory for the specified attribute.

**Comment by gdbarron** [comment]
Thanks for the feedback.  I've just added Get-TppIdentityAttribute and integrated it into Get-TppPermission as well, #52.  Looks like there's very few attributes that can actually be retrieved so if there's more than documented on Venafi's site, please let me know and we can add them.

**Comment by Saadi6** [comment]
ReadAttribute will read and return the value of any default or custom attribute in the directory. Value with data type of binary is converted to base64 by TPP.

**Comment by gdbarron** [comment]
the documentation says otherwise, just want to confirm.  Here's what it says

> 

AttributeName | The attribute that describes a person or group:For a Group: specify Group Membership.For an individual identity, specify one of the following: Full Name, Internet EMail Address ,Given Name, Surname.
-- | --

I've tried "Full Name" and that didn't return a value against an AD source, but "Name" did.

**Comment by Saadi6** [comment]
Yup, the method will read and return the value of any valid attribute name from the directory. 'Full Name' is not an attribute name in the AD but 'name' is. You can use ADSI Edit to view all attributes in AD that have a value assigned. 

![image](https://user-images.githubusercontent.com/4195725/44636597-2272e380-a9f0-11e8-9a22-0006dc14f851.png)

**Comment by gdbarron** [comment]
Cool, thanks. I'll remove the limitation on the function.
