### ISSUE TITLE
New Feature Requests - Dissociate certificate and Delete certificate

### ISSUE THREAD

**Issue by mlamutt** [gdbarron/VenafiTppPS#54]
Hi, 

This is a request to add 2 new features.  

Dissociate certificate - this feature will allow dissociating all applications from a cert.  

https://docs.venafi.com/Docs/18.2SDK/TopNav/Content/SDK/WebSDK/API_Reference/r-SDK-POST-Certificates-Dissociate.php?Highlight=remove%20from%20application

My current process is:
1) get DN and GUID for a cert using Get-TppObject
     $CertInfo = Get-TppObject -Pattern $FQDN -Recursive
           $script:DN = $CertInfo.DN
           $script:GUID = $CertInfo.GUID

2) get associated applications for the cert 
    $Attitubes = Get-TppAttribute -DN $DN -AttributeName "Consumers" -EffectivePolicy
        $script:App = $Attitubes.config.value

3) use the $App array to disassociate the cert (bypassing your invoke-tpprequest):

$uri = ($TPPServer + '/vedsdk/Certificates/Dissociate')
    $Method = 'POST'
    $Body = @{
      CertificateDN = $DN
      ApplicationDN = $App
      DeleteOrphans = 'true | false'
    }
    $restBody = ConvertTo-Json $Body -depth 5
    $hdr = @{
      "X-Venafi-Api-Key" = $TppSession.ApiKey
    }

    $params = @{
      Method      = $Method
      Uri         = $uri
      Headers     = $hdr
      Body        = $restBody
      ContentType = 'application/json'
    }

    Write-Verbose ($params | ConvertTo-Json | out-string)
    
    try {
      $request = Invoke-RestMethod @params
....

Delete certificate - once all associations have been removed:

https://docs.venafi.com/Docs/18.2SDK/TopNav/Content/SDK/WebSDK/API_Reference/r-SDK-DELETE-Certificates-Guid.php?Highlight=delete%20certificate

The DELETE Certificates/{guid} will also remove the associations, but as I wanted that as a standalone option (for use when not deleting a cert), I am calling it first.

1) using the quid, call  'DELETE https://tpp.venafi.example/vedsdk/Certificates/{quid}':

$uri = ($TPPServer + '/vedsdk/Certificates/' + $GUID)
    $Method = 'DELETE'
    $hdr = @{
      "X-Venafi-Api-Key" = $TppSession.ApiKey
    }

    $params = @{
      Method      = $Method
      Uri         = $uri
      Headers     = $hdr
      ContentType = 'application/json'
    }

    Write-Verbose ($params | ConvertTo-Json | out-string)

    try {
      $request = Invoke-RestMethod @params
...
thanks

**Comment by gdbarron** [comment]
Thanks for the suggestions, I'll put this next in queue.

If you'd like, I've tried to implement pipeline support as much as possible so you could simplify your first 2 steps with

`$App = (Get-TppObject -Pattern $FQDN | Get-TppAttribute -AttributeName "Consumers" -EffectivePolicy).config.value`

Reading through your post I realized there is a bug in Get-TppObject so thanks for that :)  A pattern search is recursive by default so providing the `-Recursive` parameter doesn't get you anything additional and might be misleading.  My parameters didn't truly reflect that.  I've updated the code, #55, to fix the parameters.  This means the latest won't accept `-Pattern` and `-Recursive` without providing `-Path`.  Or, you can just provide `-Pattern` and it will search everything which looks to be your intended use.

**Comment by gdbarron** [comment]
@mlamutt, I've added Remove-TppCertificateAssociation, #56.  Included is a -RemoveAll option which may be of use.  Your code would look like

`Get-TppObject -Pattern $FQDN | Remove-TppCertificateAssociation -RemoveAll`

Also, I might suggest using the -Class parameter of Get-TppObject to ensure you don't pick up objects which match the pattern, but aren't certs.

Here's the [updated module](https://www.powershellgallery.com/packages/venafitppps/0.5.2).

**Comment by mlamutt** [comment]
@gdbarron - thanks for the work and the info.  Ill take a look at the new module, and your suggestions.

**Comment by gdbarron** [comment]
@mlamutt, remove and many other updates in #61, version 0.6.0.
