### ISSUE TITLE
Ensure inherited Master Admin perms aren't removed/overwritten

### ISSUE THREAD

**Issue by gdbarron** [gdbarron/VenafiTppPS#57]
Creating issue from comment in #53 by @saadi6

Just FYI - see below from 18.2 release notes. Looks like others had the same issue. I suggested having a test in your function to ensure inherited Master Admin permissions are not overwritten with lesser privileges. This change in v18.2 checks the same thing but it would still be worthwhile having this test in the function to cater for older version of TPP. Also, I'm unsure if below is applicable to permissions set via the API.

_Master Admins Permissions Changed

Beginning with release 18.2, Master Admins can no longer have their permissions accidentally or intentionally removed at certain portions of the policy tree. This change occurred because of the number of customers unintentionally making changes to the permissions of Master Admin accounts which resulted in a call to a Venafi Support Engineering to reverse the problem. Adding extra permissions to Master Admins causes considerable slow downs for Aperture, WebAdmin, and WhyCustom Reports created by that user. By completely removing the ability to change Master Admins permissions in subsets of the tree, all Master Admins will see an increased performance benefit. It is important to note that when managing permissions, it is still possible to add Master Admins to the permissions control for a specific object and its children, but those permissions assignments will be ignored._

**Comment by BeardedPrincess** [comment]
@gdbarron ... I suggest closing this. With 20.2 being released soon, this issue will go away as 18.2 will be falling out of support. 

@Saadi6 any issues with closing this?

**Comment by Saadi6** [comment]
Yes, I believe this issue can be closed. It was an edge case anyway.

**Comment by gdbarron** [comment]
Thanks guys.
