### ISSUE TITLE
Reading attributes from Get-TppIdentityAttribute.ps1

### ISSUE THREAD

**Issue by Saadi6** [gdbarron/VenafiTppPS#59]
Hi @gdbarron . The Identity/ReadAttribute method used by Get-TppIdentityAttribute function cannot read every attribute from the directory. My apologies for stating differently before - it was based on limited testing. While this method reads most of the attributes, not all of them return a value even when it exists in the directory. For e.g. ObjectSid, ObjectGUID, ObjectClass and ObjectCategory return a value but objectCategory returns null.

You may keep the inputs and validation of this function the same but note that it may or may not return a value, even when it is present in the directory or limit the choices of attributes to those present in the documentation.

I will let you know if I find out why TPP does not return values for some attributes. 

Regards.

**Comment by gdbarron** [comment]
Thanks for the update, @Saadi6.  I've already removed the parameter validation and we can leave as is given there isn't an exception thrown when a value doesn't exist, the user will just get null.  If we can narrow in on a set of attributes we know are valid, we can look to revisit.
