### ISSUE TITLE
possible challenge with Get-TppIdentityAttribute

### ISSUE THREAD

**Issue by JohnnyTSi** [gdbarron/VenafiTppPS#72]
Hi Greg,

This PowerShell module is awesome, Thanks for the contribution. I'm trying to build a custom scripted solution for an in-house app and have almost everything working, I'm able to use Get-TppCertificateDetail to collect a certificate's properties including DN, Expiration Date, Issuer, the list of SAN's and consumers (host names)

I'm stuck however on getting the list of contacts associated with the certificate. I'm using a foreach loop to parse through the list of UniversalIDs collecting the Name property of each contact.

##### begin code snip ######
$contacts = $CertProperties.Contact
$IDs = $null
foreach ($UniversalID in $contacts ) {
	$IDs += (Get-TppIdentityAttribute -PrefixedUniversalId $UniversalID -TppSession $Session -Attribute Name | select -ExpandProperty Attribute).Name #line 101
	$CertContacts += $IDs
	$IDs
	$UniversalID
	}
#### End Code Snip ####

Example output with error(s) below:

local:{ab92b6aa-0670-4070-8771-6eeb702d6beb}
Get-TppIdentityAttribute : Cannot validate argument on parameter 'PrefixedUniversalId'. The "
                $_ -match '(AD|LDAP)+\S+:\w{32}$' -or $_ -match 'local:\w{8}-\w{4}-\w{4}-\w{4}-\w{12}$'
            " validation script for the argument with value "AD+DOMAIN Forest:065380f0bb3e9847bba614e2f7718756" did not 
return a result of True. Determine why the validation script failed, and then try the command again.
At C:\Scripts\Venafi\VenafiCertExpirationQuery2AppLogDebugv1.3.ps1:101 char:68
+ ... = (Get-TppIdentityAttribute -PrefixedUniversalId $UniversalID -TppSes ...
+                                                      ~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-TppIdentityAttribute], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Get-TppIdentityAttribute
 
AD+DOMAIN Forest:065380f0bb3e9847bba614e2f7718756
Get-TppIdentityAttribute : Cannot validate argument on parameter 'PrefixedUniversalId'. The "
                $_ -match '(AD|LDAP)+\S+:\w{32}$' -or $_ -match 'local:\w{8}-\w{4}-\w{4}-\w{4}-\w{12}$'
            " validation script for the argument with value "AD+DOMAIN Forest:0a7f39280f2b2444a1166bfe23288b77" did not 
return a result of True. Determine why the validation script failed, and then try the command again.
At C:\Scripts\Venafi\VenafiCertExpirationQuery2AppLogDebugv1.3.ps1:101 char:68
+ ... = (Get-TppIdentityAttribute -PrefixedUniversalId $UniversalID -TppSes ...
+                                                      ~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-TppIdentityAttribute], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Get-TppIdentityAttribute

Of Note:
1. I do see a discrepancy in our UniversalID in that it includes the word Forest as well as our Domain Name (Note that I've replaced our Domain name with 'DOMAIN' )
2. We do have a multi-domain AD forest with some of these contact objects in a child domain.

Thanks for your help.
John-

**Comment by gdbarron** [comment]
Hey there @JohnnyTSi, thanks for the issue.  I definitely see some differences between your identity IDs and ones I've seen in the past.  It seems that at times there are curly braces around the identity guid/id and sometimes not.  This is the first time I'm seeing the 'AD:Domain Forest' prefix as well.  Given those are the universal IDs coming out of Venafi, I am sure they are correct, just different than environments I've used.  I've updated the validation to accept these changes so you should be good to go.

Also, I've added 'Contact' as an acceptable property name to be piped into Get-TppIdentityAttribute so you can now do `Get-TppCertificateDetail | Get-TppIdentityAttribute` directly.

The new module is [v1.0.1](https://www.powershellgallery.com/packages/VenafiTppPS/1.0.1).  Please test and let me know how it goes.

PR #73

**Comment by gdbarron** [comment]
One last thing.  Unless you are creating a session specifically with alternate credentials or to use multiple environments at the same time, there is no need to pass `-TppSession $Session`.  When you run `New-TppSession`, the session will be stored and used by default for all module functions.

**Comment by JohnnyTSi** [comment]
That seems to have resolved my challenge The function now returns expected results. - Thank you so much for the speedy turnaround on this awesome PowerShell module.

Thanks,
John-
