### ISSUE TITLE
New-TppCertificate Doesn't Provision New Certificate from CA?

### ISSUE THREAD

**Issue by jvermast** [gdbarron/VenafiTppPS#74]
I've been working on this for awhile, its entirely possible that I am missing some prerequisites...but New-TPPCertificate doesn't actually seem to request a Cert from a CA?

Ran:
New-TppCertificate -Name $CommonName -Path $certpath -CertificateAuthorityPath $caprovider -ManagementType Provisioning

In my TPP console I see the new cert but the status is:
WebSDK CertRequest Module Requested Certificate

There is no CN, Organization, OU, City, State, Province and no CSR seems to have been sent to a CA?

**Comment by gdbarron** [comment]
@jvermast, I saw this issue was closed and apologize I didn't see the notification when it was opened.  Is this still an issue or resolved?
