### ISSUE TITLE
New-TPPCertificate SAN Variable

### ISSUE THREAD

**Issue by jvermast** [gdbarron/VenafiTppPS#75]
Is it possible to add a SAN List to a new certificate request in any way?

**Comment by gdbarron** [comment]
Hi @jvermast. Looks like there [is a way](https://docs.venafi.com/Docs/19.2SDK/TopNav/Content/SDK/WebSDK/API_Reference/r-SDK-POST-Certificates-request.php?tocpath=REST%20API%20reference%7CCertificates%20programming%20interface%7CPOST%20Certificates%2FRequest%7C_____0) to provide that via the api, but the module function doesn't include it quite yet.  If you are comfortable submitting a PR that would be great.  If not, I can look to add that.

**Comment by jvermast** [comment]
Hey sorry, I probably wont have time to get into it anytime soon, let me know how you make out if you have a chance to look at it.

**Comment by gdbarron** [comment]
@jvermast, I've added this functionality in v1.0.4.  It took a bit of work, but I think I have all the validation and everything else set.  I added an example to the code, but just so you know, you'll need to pass in 1 or more hashtables to the parameter, eg.

`-SubjectAltName @{'Email'='me@x.com'},@{'IPAddress'='1.2.3.4'}`

Let me know how it goes.

**Comment by gdbarron** [comment]
@jvermast I fixed an issue with this in a recent version. Can you please confirm if this is resolved and the issue can be closed?

**Comment by jvermast** [comment]
Looks good!
