### ISSUE TITLE
Adding "Windows Authorization" option to New-TPPSession

### ISSUE THREAD

**Issue by bwright86** [gdbarron/VenafiTppPS#77]
I recently discovered this module, and am starting to test it out.

One of the first things I noticed was the Basic authentication that happens currently, albeit across an HTTPS session. So not insecure, but it isn't preferred IMO.

It looks like the newer versions of TPP (v17.3+) support Windows Authorization.

Could this new method be integrated into the New-TPPSession and underlying TPPSession class?

Here is a recent forum link about the method:
https://support.venafi.com/hc/en-us/community/posts/115000941452-Authorize

Again, I am still digesting and digging into this module, so currently excited to see what is available!

**Comment by gdbarron** [comment]
Hi @bwright86!  Windows auth is already available.  Do you have the latest version of the module?

![image](https://user-images.githubusercontent.com/11862024/64260799-867c9180-cef9-11e9-8a61-c73157706fd0.png)

**Comment by bwright86** [comment]
Thank you for the response, maybe I need to look at the code. I just installed the module yesterday 9/3 from PSGallery.

From the verbose output, it looked like it tried the old URL, and was passing user/password in the header.

Could you confirm the current version that has this?

**Comment by gdbarron** [comment]
If you installed yesterday, 9/3, it should definitely be there.  Integrated auth was introduced in v1.0 which was published in March.  Here's what you should see

![image](https://user-images.githubusercontent.com/11862024/64309327-325dc580-cf6a-11e9-83be-d5618592c35d.png)

Can you provide a sample of your command?

**Comment by bwright86** [comment]
Hmm, Now that I look again, I do see what you pointed out above. I also see the logic in the code that handles this correctly.

Somehow I may have gotten an older version at work. Let me confirm which version I pulled from PSGallery, this may be a different issue. (I did check PSGallery and I do see v1.0+ out there.)

I am glad to see this newer feature is already available in the module. Thank you in advance for the work you are doing on this module!

**Comment by gdbarron** [comment]
Sounds good.  Let me know and if it was just an older version, please close the issue.

**Comment by bwright86** [comment]
So it looks like I am running v1.0.1, so I am on a current version.

I also realized why it responded the way it did. I am trying to pass another domain’s credential, and so it is flowing as a credential to the tppsession object.

I can close this issue. But I am curious, is there an easy way to handle this scenario?

**Comment by gdbarron** [comment]
When you say 'is there an easy way to handle this scenario', what scenario are you referring to?  

Currently, the only REST auth supported by the module is to use an api key.  OAuth is available from Venafi, but I haven't implemented it yet.

**Comment by bwright86** [comment]
The scenario I was describing was being logged into one domain and authenticating to a different Active Directory domain. I would like to use Windows Authorization method with that.

This would mean accepting a PSCredential object and passing it in the Credential parameter in the Invoke-WebRequest or Invoke-RestMethod call.

**Comment by gdbarron** [comment]
"Windows Authorization" is really integrated authentication which uses the currently logged in user to authenticate.  You can't use integrated authentication as anyone other than the logged in user.  If you want to authenticate with different credentials, you can pass either a pscredential object or username and secure password.  Either via a cred object or username/password, the server will need to be aware of the domain you are trying to authenticate against and has nothing inherently to do with the module/api.

If you want to specify which user/session will be used, you can use the `-PassThru` parameter when calling `New-TppSession` and provide the output to future function calls as `-TppSession`.

**Comment by gdbarron** [comment]
@bwright86 just checking in. All good and can close this issue?

**Comment by bwright86** [comment]
Ah, yes, I am good at this point. We can close this issue.

Thank you for your help.
