### ISSUE TITLE
Unable to create new session using new 1.2.0

### ISSUE THREAD

**Issue by ferneaux** [gdbarron/VenafiTppPS#85]
Hi Greg,

Installed the 1.2.0 update today, but get an error right away when attempting to create a session.

```
$cred = Get-Credential
New-TppSession -ServerUrl https://venafi.mydomain.com -Credential $cred

Invoke-TppRestMethod : The term 'Invoke-TppRestMethod' is not recognized as the name of a cmdlet, function, script
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
At C:\Users\myUsername\Documents\WindowsPowerShell\Modules\venafitppps\1.2.0\Class\TppSession.ps1:78 char:21
+         $response = Invoke-TppRestMethod @params
+                     ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Invoke-TppRestMethod:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```
I removed the module from powershell, then deleted the 1.2.0 folder from my system. Re-imported the module and was able to log in via 1.1.0

Thanks,
Mark

**Comment by gdbarron** [comment]
Thanks, Mark.  For some odd reason it imports and runs fine via .psm1 and .psd1, but not by name and I didn't catch this in my testing.  Can you confirm you are seeing the same?

**Comment by gdbarron** [comment]
Hey Mark.  Can you give this another go with 1.2.2?  I was able to repro, but not consistently and only on Windows; Linux was fine.  I've simplified the class and enum loading process and we look to be back in business.

**Comment by ferneaux** [comment]
Hi Greg... this update seems to let me log in and do my other functions without issue. Thanks!

**Comment by gdbarron** [comment]
#87
