### ISSUE TITLE
New-TppObject -ProvisionCertificate doesn't seem to trigger a push.

### ISSUE THREAD

**Issue by jvermast** [gdbarron/VenafiTppPS#89]
I wish I could provide more information, I'm still digging through why. I'm creating a type of "Apache" and it just straight up doesn't seem to try to push when I pass the -ProvisionCertificate flag.

**Comment by jvermast** [comment]
I am of course passing a Certificate attribute DN.

**Comment by jvermast** [comment]
Was able to get around the problem with the following:

   Set-TppAttribute -Path _DN_ -AttributeName "Stage" -Value "800"
    Set-TppAttribute -Path _DN_ -AttributeName "Provisioning Work To Do" -Value "1"

**Comment by gdbarron** [comment]
Hi @jvermast.  Could you please run the command with -verbose and send me the output?  Of course hide sensitive info :)  Thanks.

**Comment by gdbarron** [comment]
Nevermind, found the issue.  v1.2.3 pushed to the gallery.  Please let me know if this solves the issue.  Thanks for reporting!

**Comment by jvermast** [comment]
Good stuff! Thanks!
