### ISSUE TITLE
Issue with "CustomFields" Get-TppCertificateDetail

### ISSUE THREAD

**Issue by macflurry7** [gdbarron/VenafiTppPS#91]
Hello,

I'm getting this...

CustomFields
------------
{@{Name=Owner Group; Type=Text; Value=System.Object[]}}

Instead of plain text value. Can you help me please... I would need to extract value from one field inside CustomFields

Thank you in advance

**Comment by gdbarron** [comment]
Hi.  Items in Venafi are often a list of strings and not just a string itself, even if there is only 1 item/value.  To get just the value, you can do something like `$var.CustomFields | where {$_.Name -eq 'Owner Group'} | Select -ExpandProperty Value`.
