### ISSUE TITLE
Find-TppCertificate does not appear to support "offset"

### ISSUE THREAD

**Issue by jmeldrum76** [gdbarron/VenafiTppPS#92]
Hi,

I have been using several of your functions, which are pretty incredible. It appears that the Find-TppCertificate function does not support offset but does support limit.  See Venafi documentation for more information. Here is a screenshot of the doc.

https://docs.venafi.com/Docs/20.1SDK/TopNav/Content/SDK/WebSDK/r-SDK-GET-Certificates.php?tocpath=Web%20SDK%20reference%7CCertificates%20programming%20interface%7C_____4

![image](https://user-images.githubusercontent.com/21229220/80813934-32a97180-8b88-11ea-9824-07f3a2f49c50.png)

Thanks for all the work you do.

Jeremy Meldrum

**Comment by gdbarron** [comment]
Hi again.  The one question I have with this is related to "paging".  The docs state to use offset and limit together to achieve paging, but doesn't state how many items are in a page.  If I use their example, I start at page 5, go to page 14 (10 pages), but how many items is that?

**Comment by gdbarron** [comment]
I did some testing and limit and offset don't seem to actually perform paging, but work as you would expect `-First` and `-Skip` to.  I've added the offset param.
