### ISSUE TITLE
Update authentication to support new token auth

### ISSUE THREAD

**Issue by BeardedPrincess** [gdbarron/VenafiTppPS#94]
Starting with TPP 20.1, the old way of getting and using the API key is being deprecated. In 20.4 /authorize will be disabled completely.

The new method for token-based authentication is much more efficient, but brings a bit of complexity with it unfortunately.  The documentation covers quite a bit of this, including some design patterns starting here: [https://docs.venafi.com/Docs/20.1SDK/TopNav/Content/SDK/AuthSDK/t-SDKa-OAuthConversionDesignPatterns.php](https://docs.venafi.com/Docs/20.1SDK/TopNav/Content/SDK/AuthSDK/t-SDKa-OAuthConversionDesignPatterns.php)

Opening this issue to start tracking this for the project.  I'll also make myself available to assist (will try and get a PR submitted in the next week or so to get us rolling).

**Comment by gdbarron** [comment]
working branch: https://github.com/gdbarron/VenafiTppPS/tree/may25-oauth-support

**Comment by gdbarron** [comment]
@BeardedPrincess, 20.1 documentation, https://docs.venafi.com/Docs/20.1/TopNav/Content/SDK/AuthSDK/r-SDKa-POST-Authorize-Integrated.php?tocpath=Topics%20by%20Guide%7CDeveloper%27s%20Guide%7CAuth%20SDK%20reference%20for%20token%20management%7C_____10, states token-based authorize/integrated requires username/password.  I'd expect it to use default credentials.  Can you please confirm?

**Comment by gdbarron** [comment]
Nevermind, looks like my hunch was correct.  I've submitted a documentation update.

**Comment by gdbarron** [comment]
@BeardedPrincess, I'm trying to add token refresh functionality.  The documentation states client_id is optional, https://docs.venafi.com/Docs/20.1/TopNav/Content/SDK/AuthSDK/r-SDKa-POST-AuthorizeToken.php?tocpath=Topics%20by%20Guide%7CDeveloper%27s%20Guide%7CAuth%20SDK%20reference%20for%20token%20management%7C_____12, but when I make the call without it I get the following:
![image](https://user-images.githubusercontent.com/11862024/83052469-5c39a980-a01d-11ea-8c67-ac637ae4beb8.png)
Is this a bug?

**Comment by BeardedPrincess** [comment]
Hmm... it seems odd to me that would be optional.. does it work when you provide the client_id?  Also, would be interesting to know if it works when you supply a wrong client_id.  I'll see if I can do some testing as well and can open a doc bug if necessary.

**Comment by gdbarron** [comment]
If any client_id, valid or invalid, is provided, it works.  Sounds like a code and doc bug.

**Comment by BeardedPrincess** [comment]
Thanks for the update @gdbarron ... I have confirmed the same on my end and reported this issue (internal tracking #VEN-59825).

**Comment by gdbarron** [comment]
Thanks for the heads up.  If and when you are ready, the working branch is good to test token auth with.

**Comment by gdbarron** [comment]
@BeardedPrincess, no matter what I try, post calls are fine, get calls all seem to fail with 
![image](https://user-images.githubusercontent.com/11862024/83071816-b6e1fe00-a03b-11ea-8801-7f362ed8f230.png)
I have tried many permutations of it in the header and body, but no go.  Thoughts?

**Comment by BeardedPrincess** [comment]
Thank you sir! I'll try and give it a whirl this evening... I'll see if I can get some other eyes on it from my team as well.

**Comment by BeardedPrincess** [comment]
Something is definitely up... I can reproduce this bypassing the module altogether... when the exact same thing works from Postman just fine... 
![image](https://user-images.githubusercontent.com/28336998/83080517-a9c50f00-a03b-11ea-968b-3d4e6316148e.png)

**Comment by BeardedPrincess** [comment]
@gdbarron I was able to get to the bottom of this, after I was pointed to this addition in the documentation:

From https://docs.venafi.com/Docs/20.1SDK/TopNav/Content/SDK/WebSDK/r-SDK-GET-Certificates.php:
```When adding query parameters, use the /? syntax. If you are not passing any parameters, make sure the URL ends with a trailing slash. Otherwise, some environments, such as cURL and PowerShell, return a HTTP 307 Temporary Redirect message.```

This will affect the following calls:
•	GET certificates/
•	HEAD certificates/
•	GET client/
•	GET client/details/
•	GET client/work/
•	POST log/
•	GET pki/hashicorp/ca/
•	POST pki/hashicorp/ca/
•	POST pki/hashicorp/role/
•	GET processingengines/
•	POST teams/

**Comment by Saadi6** [comment]
Hi @BeardedPrincess and @gdbarron . Can you try adding a front slash to your URI when making a GET call having OAuth token? For e.g. https://tls.bigsur.local/vedsdk/certificates**/**. 
I came across this a while ago but didn't get a chance to dig deeper. If you can, please have a look at the log on IIS to see if there is a difference in the logged URI b/w POST and GET requests. Not sure if its PowerShell gaslighting us or a bug in TPP.

**Comment by gdbarron** [comment]
Looks like you both posted at the same time @BeardedPrincess and @Saadi6!  That seems to do the trick, thanks.  I didn't get a 307 though, I got a 401.

For my own knowledge, I'm curious why this is required on some api calls and not others.  eg., why required on POST /Log/, but not GET /Log?

**Comment by BeardedPrincess** [comment]
@gdbarron I think POST /log may actually not require it... I copied and pasted that list from an email, I think it should be GET /log instead. 

I'm _thinking_, just by looking at the list (haven't checked them all) the reason for those are because there are other API endpoints with things after the / (i.e. GET /certificates/ vs. GET /certificates/{guid}/ or GET /log/ vs. GET /log/{guid}/).

I think (would need a packet capture to confirm) the reason you're seeing a 401 is that the call first hits the webserver, gets a 307 redirect, which 'adds' the trailing /, but then PowerShell (and presumably cURL) remove the Authorization header on redirect as a security mechanism. At least that's how it was explained to me.

**Comment by Saadi6** [comment]
I can't explain why PowerShell 5.1 removes Authorization header with a bearer token which was added as a dictionary object. Support for token based auth was not added until v6.x so it seems strange that a custom header is dumped as a 'security mechanism' when v5.1 doesn't understand its purpose - unless the redirect always clears the entire header. If someone does take the time to figure it out then let me know! To avoid errors I just made sure that all GETs that didn't include querystrings use a trailing slash.

**Comment by gdbarron** [comment]
@BeardedPrincess, your explanation as to why I'm getting a 401 makes complete sense and was actually my thought as well.  The docs are what threw me off.  They explicitly mention powershell and that a 307 would be received without a trailing slash, but that's not what I got.

It sounds like @Saadi6's approach is the way to go, GETs with no querystring get a trailing slash.  I'll follow that logic until we find more use cases :)

**Comment by gdbarron** [comment]
That update is in, https://github.com/gdbarron/VenafiTppPS/commit/bf5bccc6cbf11e26ef0b78e72b9860d89276b8ee.

**Comment by gdbarron** [comment]
After some testing, unfortunately, this logic does not work.  eg., GET SystemStatus/Version/ fails.  My assumption is that the trailing slash needs to be added to GETs with no querystring only when that api has parameters that can be provided to it.  GET /SystemStatus/Version has no parameters and works fine w/o a trailing slash as does /certificates/{guid}.

**Comment by gdbarron** [comment]
Agree it will be challenging, but I like the idea of having as few api calls as possible.  I've merged together the 2 ideas and will try with a trailing slash if the first call fails, but ask the person who comes across it to create an issue so I can fix it.
```
        try {
            Invoke-RestMethod @params
        } catch {
            if ( $Method -eq 'Get' -and (-not $uri.EndsWith('/')) ) {

                Write-Verbose 'GET call failed, trying again with a trailing slash'

                $params.Uri += '/'

                try {
                    Invoke-RestMethod @params
                    Write-Warning ('GET call requires a trailing slash, please create an issue at https://github.com/gdbarron/VenafiTppPS/issues and mention api endpoint {0}' -f ('{1}/{2}' -f $UriRoot, $UriLeaf))
                } catch {
                    throw ('"{0} {1}: {2}' -f $_.Exception.Response.StatusCode.value__, $_.Exception.Response.StatusDescription, $_ | Out-String )
                }
            } else {
                throw ('"{0} {1}: {2}' -f $_.Exception.Response.StatusCode.value__, $_.Exception.Response.StatusDescription, $_ | Out-String )
            }
        }
```

**Comment by BeardedPrincess** [comment]
@gdbarron I noticed today in playing with this that there is an option `PreserveAuthorizationOnRedirect` on Invoke-RestMethod that looks like it was introduced in PowerShell 6. Maybe that makes this all easier?

Also, I'm thinking about a different strategy for this Token-based auth.. would like to get your take:

The point of the token-auth is that you don't need to store/keep a username/password to run your script.  This is especially useful when setting something up to run in an automated way (like from another service or app, or when a script is run by cron or something).  

I'm thinking about introducing a Grant-TPPToken call, which will just be used to get the token(s) once. The access token is good for 90 days, and the refresh token 6 months IIRC.  Also, this should be paired with a Revoke-TPPToken, so you can trash those if you're done with them (cause they're good for a long time).  Then, in New-TPPSession, it either takes a username/password like it does now to use the old API key way, or just the access token (and optionally the refresh token if it's going to persist longer than 90 days). 

Thoughts?  (I'm working on putting these changes into a PR right now, but I'm not nearly as fast as you!)

**Comment by gdbarron** [comment]
@BeardedPrincess, thanks for your thoughts.  I'll definitely have a look at PreserveAuthorizationOnRedirect, but I know many folks still haven't gotten to ps core yet and I wouldn't want to exclude them.

Not sure if you've seen the changes I've put into the working branch, but I've already included updates for token-based auth and am no longer storing credentials.  You might want to check it out before you spend the time coding it up.  New-TppSession now handles api keys and tokens.  The Api Key method still stores the credentials, but the token-based one does not.  Whereas refreshes were done with stored credentials previously, it is now done via the refresh token.  I haven't added revoke-tpptoken yet, but will look to do so.  Let me know if you have feedback on what I've done so far.

**Comment by BeardedPrincess** [comment]
Thanks @gdbarron - I'm working from your latest committed changes in that branch.  The token auth stuff is a bit weird, I think we need to handle it slightly differently than the old API keys.  I think it'll be easier to show you when I get it to a decent working state.

Also, an FYI. I have opened a few new ideas on https://ideas.venafi.com based on playing around with this. The token-based auth needs a few things, along with the API in general:

https://ideas.venafi.com/forums/916237-platform/suggestions/40564615-implement-vedauth-checkvalid-for-token-based-api

https://ideas.venafi.com/forums/916237-platform/suggestions/40564288-api-token-based-authentication-should-return-refr

https://ideas.venafi.com/forums/916237-platform/suggestions/40564636-modify-get-systemstatus-version-api-call-to-not-re

**Comment by Saadi6** [comment]
Just a note that TPP uses non-core version (so 5.1 max) if the PowerShell code is launched from TPP itself. This is not a problem if VenafiTppPS is launched directly from PowerShell, however, if it is incorporated into TPP's scripting extension (Adaptable Framework), we are limited to methods and parameters available in v5.1. 

https://ideas.venafi.com/forums/916237-platform/suggestions/40566262-support-for-ps-core

**Comment by gdbarron** [comment]
@BeardedPrincess, lots of updates published if you wanted to have a look before I pushed to the gallery.

**Comment by BeardedPrincess** [comment]
@gdbarron I've pulled the latest and am playing around with it. So far so good. I like the direction you went on this. 

I do think we still want to add one standalone function for refreshing the access token (so the toolset for managing that is complete).

**Comment by gdbarron** [comment]
I'll look to add refresh functionality in a future revision.
