### ISSUE TITLE
Include Private Key in Base64 PKCS #8

### ISSUE THREAD

**Issue by azirish1998** [gdbarron/VenafiTppPS#95]
You can export the private key in Base64 PKCS #8.  Please remove this error check to disallow it.

**Comment by gdbarron** [comment]
That does look to be the case, but I guess Venafi's documentation is wrong?

> 

IncludePrivateKey (Optional) | When the Format is Base64, PKCS #12, or JKS, you can specify whether to return the private key:true: Show the corresponding private key for the Certificate DN. Requires a Password value. The private key information appears before any certificate chain of trust information.false: Omit the private key for the Certificate DN.
-- | --

**Comment by gdbarron** [comment]
@azirish1998, re-reading this, does Base64 mean both Base64 and Base64 (PKCS #8)?  I had been assuming it just meant Base64, but perhaps that's incorrect.

**Comment by gdbarron** [comment]
Looks like they updated newer versions of the documentation and specifically call out PKCS8.  I'll get this updated.
