### ISSUE TITLE
Params hash table in Get-TppCertificate

### ISSUE THREAD

**Issue by azirish1998** [gdbarron/VenafiTppPS#96]
If you're pipelining multiple objects into Get-TppCertificate and you use an option like -IncludePrivateKey, you get an error where you are trying to "re-add" the key to the hashtable.  I think you need to re-initialize the params hash in process{}

**Comment by gdbarron** [comment]
Thanks @azirish1998.  Looks like I've made that mistake in a few places, I'll get that cleaned up.
